---
version: "3"
services:
  freqtrade:
    image: 302142484185.dkr.ecr.ap-northeast-1.amazonaws.com/freqtrade_bot:latest
    build: .
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports: 
      - 8080:8080
    restart: unless-stopped
    container_name: freqtrade
    command: > 
     trade
     --logfile /freqtrade/user_data/logs/freqtrade.log
     --config /freqtrade/user_data/config.json
     --config /freqtrade/user_data/config-dev-Combined_NFIv7_SMA.json
     --strategy ProtectedZeus
