---
version: "3"
services:
  freqtrade:
    image: 302142484185.dkr.ecr.ap-northeast-1.amazonaws.com/freqtrade_bot:latest
    build: .
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - 8080:8080
    restart: unless-stopped
    container_name: freqtrade_bot
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/config-dev.json
  # ftmetric:
  #   image: ghcr.io/kamontat/ftmetric:v4.1.0-beta.9
  #   container_name: ftmetric
  #   restart: on-failure
  #   environment:
  #     - FTH_FREQTRADE__URL=http://freqtrade:8080
  #     # TODO: make it secure
  #     - FTH_FREQTRADE__USERNAME=dev-freqtrader
  #     - FTH_FREQTRADE__PASSWORD=demo12345
  #   ports: 
  #     - 8090:8090
  #   depends_on:
  #     - freqtrade
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "wget",
  #         "--no-verbose",
  #         "--tries=1",
  #         "--spider",
  #         "http://localhost:8090/version",
  #       ]
  #     interval: 1m
  #     timeout: 1s
  #     retries: 3
  #     start_period: 15s
  # freqtrade2:
  #   image: 302142484185.dkr.ecr.ap-northeast-1.amazonaws.com/freqtrade_bot:latest
  #   build: .
  #   volumes:
  #     - "./user_data:/freqtrade/user_data"
  #   # ports:
  #     # - 8080:8080
  #   restart: unless-stopped
  #   container_name: freqtrade2
  #   command: >
  #     trade
  #     --logfile /freqtrade/user_data/logs/freqtrade.log
  #     --config /freqtrade/user_data/config.json
  #     --config /freqtrade/user_data/config-dev-Combined_NFIv7_SMA.json
  # ftmetric2:
  #   # TODO: recommend to specify version `ghcr.io/kamontat/ftmetric:vX.X.X`
  #   image: ghcr.io/kamontat/ftmetric:v4.1.0-beta.9
  #   container_name: ftmetric2
  #   restart: on-failure
  #   environment:
  #     - FTH_FREQTRADE__URL=http://freqtrade2:8080
  #     # TODO: make it secure
  #     - FTH_FREQTRADE__USERNAME=dev-freqtrader
  #     - FTH_FREQTRADE__PASSWORD=_4yA%d5Bkka5&xGH
  #   depends_on:
  #     - freqtrade
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "wget",
  #         "--no-verbose",
  #         "--tries=1",
  #         "--spider",
  #         "http://localhost:8090/version",
  #       ]
  #     interval: 1m
  #     timeout: 1s
  #     retries: 3
  #     start_period: 15s
  # prometheus:
  #   image: prom/prometheus:v2.28.0
  #   restart:
  #     on-failure
  #     # be aware before open the port
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     # TODO: add configuration at prometheus/prometheus.yml
  #     - ./prometheus/config/local:/etc/prometheus/
  #     - prometheus-data:/prometheus
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "wget",
  #         "--no-verbose",
  #         "--tries=1",
  #         "--spider",
  #         "http://localhost:9090/-/healthy",
  #       ]
  #     interval: 1m
  #     timeout: 1s
  #     retries: 3
  #     start_period: 15s

  # grafana:
  #   image: grafana/grafana:8.0.3
  #   container_name: grafana
  #   restart: on-failure
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - freqtrade
  #     - prometheus
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   environment:
  #     ## override server url
  #     # - GF_SERVER_ROOT_URL=http://example.com
  #     - GF_SERVER_HTTP_PORT=3000
  #     ## enabled grafana beta alert manager
  #     - GF_FEATURE_TOGGLES_ENABLE=ngalert
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=verygrafanapassword
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "wget",
  #         "--no-verbose",
  #         "--tries=1",
  #         "--spider",
  #         "http://localhost:3000/api/health",
  #       ]
  #     interval: 1m
  #     timeout: 1s
  #     retries: 3
  #     start_period: 15s

# volumes:
#   grafana-data:
#   prometheus-data:
