FROM freqtradeorg/freqtrade:develop

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
# USER root

# Install postgresql driver and pandas-ta for strategy
RUN pip install --user psycopg2-binary pandas-ta ta

# USER ftuser