FROM freqtradeorg/freqtrade:stable

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
# USER root

RUN pip install --user psycopg2-binary ta

# USER ftuser